name: ChatAutoMod
version: '1.0-SNAPSHOT'
main: org.Ch0p5h0p.chatAutoMod.ChatAutoMod
api-version: '1.21'
commands:
  automodstring:
    description: "Gets the current regex master string"
    usage: "/automodstring"
  automodreload:
    description: "Reloads all config files, the recompiles the master string"
    usage: "/automodreload"
